### ISSUE TITLE
how install in arduino ide

### ISSUE THREAD

**Issue by XanBrun** [Johboh/EspNowNetwork#5]
Hello, I get an installation error, when I try to install in arduino ide, I also lack dependencies to libraries, could you explain to me how to install in ide 1.18.9
Thank you

**Comment by Johboh** [comment]
Hi!
Can you paste/show the error you are getting?

**Comment by XanBrun** [comment]
Hello
 First of all, thank you for answering.

I downloaded the repository from GitHub in zip format. When I try to include it as a library in the library manager, it does not recognize the file as a valid zip library.

Error message: Arduino:1.8.19 (Windows 10), Card:"ESP32-WROOM-DA Module, Default 4MB with spiffs (1.2MB APP/1.5MB SPIFFS), 240MHz (WiFi/BT), QIO, 80MHz, 4MB (32Mb), 921600, Core 1, Core 1, None, Disabled"

The folder or zip file does not contain a valid library

The folder or zip file does not contain a valid library

This report could contain more information with
"Show detailed output during compilation"
option enabled in File -> Preferences.

**Comment by XanBrun** [comment]
Hello again

I've tried to run the Arduino example

EspNowNetwork/examples/arduino
/host_driver/
  adding the libraries manually, but I don't have much programming experience, so in the end I can't get it to run, aemas tells me that libraries like iMQTTRemote.h are missing

I have tried it with platforming in VCE, but I do not have the necessary knowledge to execute it

Thank you

**Comment by Johboh** [comment]
I will take a look during the weekend.
It was a long time ago since I tested it with Arduino IDE, as I use Platform IO these days.

**Comment by XanBrun** [comment]
HELLO, I HAVE SOLVED IT, was to copy all the C++ files to the SCR directory

Thank you

Now I just have to understand it well and use it

**Comment by Johboh** [comment]
Ok good!
I'm planning to look into publishing the library to Arduino library manager tomorrow.

Check out the [examples](https://github.com/Johboh/EspNowNetwork/tree/main/examples/arduino) on how to use it. Readme should also be helpful.

**Comment by XanBrun** [comment]
Hello, sorry, but in the connectionhelper, ota_html.h is missing

**Comment by Johboh** [comment]
I have published libraries to Arduino IDE library manager, so you can now install the libraries that way (and remove your local install). It will take a day for them to be picked up by the library manager scraper however. They should work, but there might be issues (I have not been able to test as I'm waiting for publish).

**Comment by Johboh** [comment]
These libraries are now available to install via Arduino IDE library manager.
